// The three static asset indexes, generated by tools/gen_asset_index.py.
//
// They exist so startup costs three small TSV reads instead of parsing 11 MB of
// grammar JSON: the app knows every grammar's scope and extensions, and every
// theme's name/type/swatch, without loading any of them. Grammar JSON is read
// lazily by the native SourceLoader on first use; theme JSON only when selected.
package dev.cope.ide.core

/** One bundled theme, as described by index/themes.tsv. */
public data class ThemeEntry(
    /** Asset-relative path under `themes/`, e.g. "dark/some-theme.json". */
    public val file: String,
    public val isDark: Boolean,
    /** How many of the 40 chrome colour keys the theme actually defines. */
    public val uiCovered: Int,
    /** tokenColors rules mentioning punctuation/operator scopes. */
    public val punctuationRules: Int,
    /** Curation score; the highest-scoring dark/light themes are the defaults. */
    public val score: Int,
    public val backgroundArgb: Int,
    public val foregroundArgb: Int,
    public val accentArgb: Int,
    public val name: String,
) {
    public val assetPath: String get() = "themes/$file"
}

public class AssetIndex(
    public val themes: List<ThemeEntry>,
    public val defaultDark: String?,
    public val defaultLight: String?,
    /** Raw grammars.tsv, handed to the native engine verbatim. */
    public val grammarIndexTsv: String,
    /** extension (lowercase, no dot) -> grammar scope name. */
    public val extensionToScope: Map<String, String>,
) {
    public fun themeByFile(file: String?): ThemeEntry? =
        if (file == null) null else themes.firstOrNull { it.file == file }

    /** Language label for the status strip: "C++", "Python", ... or "Plain text". */
    public fun languageOf(fileName: String): String {
        val ext = fileName.substringAfterLast('.', "").lowercase()
        val scope = extensionToScope[ext] ?: return "Plain text"
        return LANGUAGE_NAMES[scope] ?: prettyScope(scope)
    }

    private fun prettyScope(scope: String): String =
        scope.removePrefix("source.").removePrefix("text.")
            .split('.', '-')
            .first()
            .replaceFirstChar { it.uppercase() }

    public companion object {
        /** Names worth spelling correctly; everything else derives from the scope. */
        private val LANGUAGE_NAMES: Map<String, String> = mapOf(
            "source.c" to "C",
            "source.cpp" to "C++",
            "source.cs" to "C#",
            "source.css" to "CSS",
            "source.go" to "Go",
            "source.java" to "Java",
            "source.js" to "JavaScript",
            "source.json" to "JSON",
            "source.kotlin" to "Kotlin",
            "source.lua" to "Lua",
            "source.php" to "PHP",
            "source.python" to "Python",
            "source.ruby" to "Ruby",
            "source.rust" to "Rust",
            "source.shell" to "Shell",
            "source.sql" to "SQL",
            "source.swift" to "Swift",
            "source.ts" to "TypeScript",
            "source.yaml" to "YAML",
            "text.html.basic" to "HTML",
            "text.html.markdown" to "Markdown",
            "text.xml" to "XML",
        )

        /**
         * Grammars that ship no `fileTypes` because the tmLanguage idiom leaves the
         * mapping to the editor. This is the SAME map `Engine::applyCanonicalExtensions`
         * applies in cope_jni.cpp and `applyCanonicalExtensionMap` applies in the
         * CLI; the three must be changed together.
         *
         * Without it the app knows no extension for javascript, python, html, css,
         * c, cpp, json or markdown — the status strip would say "Plain text" for a
         * .cpp file even though the native side tokenizes it correctly.
         *
         * Applied only when the index actually contains the target scope, so a
         * trimmed asset tree maps nothing rather than mapping to a missing grammar.
         */
        private val CANONICAL_EXTENSIONS: List<Pair<String, String>> = listOf(
            "js" to "source.js",
            "mjs" to "source.js",
            "cjs" to "source.js",
            "jsx" to "source.js",
            "ts" to "source.ts",
            "tsx" to "source.ts",
            "php" to "source.php",
            "html" to "text.html.basic",
            "htm" to "text.html.basic",
            "css" to "source.css",
            "scss" to "source.css",
            "less" to "source.css",
            "py" to "source.python",
            "pyi" to "source.python",
            "json" to "source.json",
            "c" to "source.c",
            "h" to "source.c",
            "cpp" to "source.cpp",
            "cc" to "source.cpp",
            "hpp" to "source.cpp",
            "cxx" to "source.cpp",
            "hxx" to "source.cpp",
            "ino" to "source.cpp",
            "md" to "text.html.markdown",
            "markdown" to "text.html.markdown",
        )

        public val EMPTY: AssetIndex = AssetIndex(
            themes = emptyList(),
            defaultDark = null,
            defaultLight = null,
            grammarIndexTsv = "",
            extensionToScope = emptyMap(),
        )

        /**
         * Parses the three index files. Every field is optional and a malformed
         * line is skipped: a truncated index must degrade to fewer themes, not a
         * crash on startup.
         */
        public fun parse(
            grammarsTsv: String,
            themesTsv: String,
            defaultsTsv: String,
        ): AssetIndex {
            val extensions = LinkedHashMap<String, String>()
            val knownScopes = HashSet<String>()
            for (line in grammarsTsv.lineSequence()) {
                if (line.isEmpty()) continue
                val parts = line.split('\t')
                if (parts.size < 3) continue
                val scope = parts[0]
                if (scope.isEmpty()) continue
                knownScopes += scope
                for (ext in parts[2].split(',')) {
                    if (ext.isNotEmpty()) extensions.putIfAbsent(ext, scope)
                }
            }
            // The canonical map wins over a fileTypes claim: a grammar that also
            // lists "js" is a fragment or a dialect, and source.js is the one the
            // native side will pick.
            for ((ext, scope) in CANONICAL_EXTENSIONS) {
                if (knownScopes.contains(scope)) extensions[ext] = scope
            }

            val themes = ArrayList<ThemeEntry>()
            for (line in themesTsv.lineSequence()) {
                if (line.isEmpty()) continue
                val parts = line.split('\t')
                if (parts.size < 9) continue
                themes += ThemeEntry(
                    file = parts[0],
                    isDark = parts[1] == "1",
                    uiCovered = parts[2].toIntOrNull() ?: 0,
                    punctuationRules = parts[3].toIntOrNull() ?: 0,
                    score = parts[4].toIntOrNull() ?: 0,
                    backgroundArgb = parseHexColor(parts[5]),
                    foregroundArgb = parseHexColor(parts[6]),
                    accentArgb = parseHexColor(parts[7]),
                    name = parts[8],
                )
            }

            var dark: String? = null
            var light: String? = null
            for (line in defaultsTsv.lineSequence()) {
                val parts = line.split('\t')
                if (parts.size < 2) continue
                when (parts[0]) {
                    "defaultDark" -> dark = parts[1]
                    "defaultLight" -> light = parts[1]
                }
            }

            return AssetIndex(
                themes = themes,
                defaultDark = dark,
                defaultLight = light,
                grammarIndexTsv = grammarsTsv,
                extensionToScope = extensions,
            )
        }

        /** "#rrggbbaa" (as written by the generator) -> ARGB int; 0 when absent. */
        public fun parseHexColor(text: String): Int {
            if (text.length != 9 || text[0] != '#') return 0
            val value = text.substring(1).toLongOrNull(16) ?: return 0
            val rgb = ((value ushr 8) and 0xFFFFFF).toInt()
            val alpha = (value and 0xFF).toInt()
            return (alpha shl 24) or rgb
        }
    }
}
