#!/usr/bin/env python3
"""Generate DisplayWidth.kt from the engine's width tables.

Why
---
The editor is a character grid: x = displayColumn * advanceWidth. Hit-testing a
tap and laying out a line therefore need the same "how many cells does this
codepoint take" answer the C++ side gives, and one JNI call per codepoint per
frame is not an option.

Rather than hand-copy ~130 ranges into Kotlin (and let them drift), this parses
src/text/utf8.cpp and emits the Kotlin tables. Re-run it whenever the C++ tables
change:

    python3 tools/gen_width_tables.py

Parsing is deliberately dumb: it finds the two constexpr Range arrays by name and
reads every {0xLO, 0xHI} pair up to the closing "};". A change to the C++ table
shape makes this fail loudly instead of emitting something wrong.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "text", "utf8.cpp")
OUT = os.path.join(
    ROOT, "android", "app", "src", "main", "kotlin", "dev", "cope", "ide", "core",
    "DisplayWidth.kt",
)

PAIR_RE = re.compile(r"\{\s*(0x[0-9A-Fa-f]+)\s*,\s*(0x[0-9A-Fa-f]+)\s*\}")


def table(text, name):
    start = text.find("constexpr Range %s[] = {" % name)
    if start < 0:
        raise SystemExit("table %s not found in utf8.cpp" % name)
    end = text.find("};", start)
    if end < 0:
        raise SystemExit("unterminated table %s" % name)
    pairs = [(int(lo, 16), int(hi, 16)) for lo, hi in PAIR_RE.findall(text[start:end])]
    if not pairs:
        raise SystemExit("table %s parsed empty" % name)
    for i in range(1, len(pairs)):
        if pairs[i][0] <= pairs[i - 1][1]:
            raise SystemExit("table %s is not sorted/disjoint at entry %d" % (name, i))
        if pairs[i][0] > pairs[i][1]:
            raise SystemExit("table %s has an inverted range at entry %d" % (name, i))
    return pairs


def emit(name, pairs, out):
    out.append("private val %s = intArrayOf(" % name)
    line = "    "
    for lo, hi in pairs:
        piece = "0x%X, 0x%X, " % (lo, hi)
        if len(line) + len(piece) > 96:
            out.append(line.rstrip())
            line = "    "
        line += piece
    if line.strip():
        out.append(line.rstrip().rstrip(","))
    out.append(")")
    out.append("")


def main():
    with open(SRC, "r", encoding="utf-8") as handle:
        text = handle.read()
    zero = table(text, "kZeroWidth")
    wide = table(text, "kWide")

    out = [
        "// GENERATED by tools/gen_width_tables.py from src/text/utf8.cpp — do not hand-edit.",
        "//",
        "// The editor lays text out as a character grid, so it must agree with the",
        "// engine's Document::displayColumnOf byte for byte: combining marks take zero",
        "// cells, East Asian wide and emoji take two, a tab advances to the next",
        "// multiple of the tab width. Disagreeing here would put the caret one cell away",
        "// from where an edit actually lands.",
        "package dev.cope.ide.core",
        "",
        "/** Cells occupied by `cp`: 0 for combining marks, 2 for wide/emoji, else 1. */",
        "public fun displayWidthOf(cp: Int): Int = when {",
        "    cp < 0x0300 -> 1 // fast path: ASCII and Latin-1 are never 0 or 2 cells",
        "    inRanges(cp, ZERO_WIDTH) -> 0",
        "    inRanges(cp, WIDE) -> 2",
        "    else -> 1",
        "}",
        "",
        "private fun inRanges(cp: Int, ranges: IntArray): Boolean {",
        "    var lo = 0",
        "    var hi = ranges.size / 2",
        "    while (lo < hi) {",
        "        val mid = lo + (hi - lo) / 2",
        "        when {",
        "            cp < ranges[mid * 2] -> hi = mid",
        "            cp > ranges[mid * 2 + 1] -> lo = mid + 1",
        "            else -> return true",
        "        }",
        "    }",
        "    return false",
        "}",
        "",
    ]
    emit("ZERO_WIDTH", zero, out)
    emit("WIDE", wide, out)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out).rstrip() + "\n")
    print("zero-width ranges: %d" % len(zero))
    print("wide ranges:       %d" % len(wide))
    return 0


if __name__ == "__main__":
    sys.exit(main())
